apiVersion: v1
kind: Pod
metadata:
  name: edge-microgateway-second
  labels:
    app: edge-microgateway 
spec:
  restartPolicy: Never
  containers:
    - name: edge-microgateway
      image: <container registory location>//microgateway:second
      ports:
        - containerPort: 8000
      env:
        - name: EDGEMICRO_ORG
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgorg
        - name: EDGEMICRO_ENV
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgenv
        - name: EDGEMICRO_KEY
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgkey
        - name: EDGEMICRO_SECRET
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgsecret
        - name: EDGEMICRO_CONFIG_DIR
          value: /home/microgateway/.edgemicro
