apiVersion: v1
kind: Secret
metadata:
  name: mgwsecret
type: Opaque
data:
  mgorg: aWNhaS1ldmFs
  mgenv: dGVzdA==
  mgkey: OWQ1NTVlN2RkNmY3MDA0YmRlMTI3MTVlNzcyNjdmN2IzNzIxZDQxYWZmM2U0Y2FlODU2ZTYyZWRjZWQxMGQ5Yg==
  mgsecret: ZGExOGYyNmM2ZDJiNTE2OGMyNzJhODlhMWNlYTBjOTQ1ODkzMTg0NTVjMWM5MjFmNmY1ZGNjODVhZTYzMTJkOQ==
