apiVersion: v1
kind: Secret
metadata:
  name: mgwsecret
type: Opaque
data:
  mgorg: YW1lci1kZW1vMTM=
  mgenv: dGVzdA==
  mgkey: OGFkOGM1NDQxYzNkNDg5N2JhNTQ3NWY2ZGUwMDA2ZmVmYzc4MWMyNzEzM2Y5YTZlZDkxY2NlMTczOTkzMjg3Nw==
  mgsecret: MWNmMDM3YzFmNWFiNGZiZDdjOGQxMzdjNGFmNzdhZjAwNjRlMDM1MDIzYWRlM2M0MDcxYWQzOGY3OGE0N2EwYw==
---
apiVersion: v1
kind: Service
metadata:
  name: edge-microgateway
  labels:
    app: edge-microgateway
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: edge-microgateway
---
apiVersion: v1
kind: Pod
metadata:
  name: edge-microgateway
spec:
  restartPolicy: Never
  containers:
    - name: edge-microgateway
      image: gcr.io/nandanks-151422/microgateway:latest
      ports:
        - containerPort: 8000
      env:
        - name: EDGEMICRO_ORG
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgorg
        - name: EDGEMICRO_ENV
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgenv
        - name: EDGEMICRO_KEY
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgkey
        - name: EDGEMICRO_SECRET
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgsecret
        - name: EDGEMICRO_CONFIG_DIR
          value: /home/microgateway/.edgemicro
